### ISSUE TITLE
This only builds the latest Release - not Nightly

### ISSUE THREAD

**Issue by eduncan911** [helfrichmichael/superslicer-novnc#4]
The README says this builds nightly of 2.4...  But, the `get_latest_superslicer_release.sh` only pulls the Releases json, which was last Sept 2022.

I'll pull the code and see if i can git clone the nightly dev branch...

**Comment by nncrypted** [comment]
Did you get this to work with latest nighly's? If so how?

**Comment by wait-what** [comment]
I got it to work, and it's really simple (it's not an elegant solution at all, so I won't be opening a pull request). Builds and runs just fine.

`get_latest_superslicer_release.sh`
```diff
-  curl -SsL https://api.github.com/repos/supermerill/SuperSlicer/releases/latest > $baseDir/latestReleaseInfo.json
+  curl -SsL https://api.github.com/repos/supermerill/SuperSlicer/releases/142041544 > $baseDir/latestReleaseInfo.json
```

On an unrelated note, maybe someone will find my `docker-compose.yaml` useful
```yaml
version: '3'

services:
  superslicer:
    # image: docker.io/mikeah/superslicer-novnc:latest
    build: ./superslicer-novnc
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
    volumes:
      - ./configs:/configs
    ports:
      - 8080:8080
```
